name: TrenchTools
author: nbdSteve
version: ${project.version}
main: com.nbdsteve.trenchtools.TrenchTools
commands:
  trench:
    usage: /<command>
    description: Type '/trench help' for command help.