#
# TrenchTools config.yml v3.1.2
# Developed by nbdSteve
#
# Plugin Support Discord: https://discord.gg/j6Yj5B8
# Read My TOS Here: https://goo.gl/mtSuZo
# Copyright Owner: nbdSteve
#
# If items from mining should go straight into the players inventory,
# rather than being dropped on the ground (Can help with lag).
enable-natural-drops: false
#
# Set this to true to enable the block blacklist.
# Set this to false to disable the block blacklist.
# The list of blocks can be edited in the trench.yml file.
enable-block-blacklist: true
#
# If this feature is enabled the plugin will auto block:
# diamond, coal and redstone
enable-auto-group: true
#
# These are values for the GUI that will be opened with the /trench command.
gui:
  #
  # The name of the GUI.
  name: "&f&lTrenchTools"
  #
  # The size of the GUI (this must be a multiple of 9).
  size: 27
  #
  # The item that will fill the GUI besides the TrenchTools.
  # Use this format: ITEM_NAME-DATA_VALUE
  fill-item: stained_glass_pane-15
  #
  # The amount of the fill item that is displayed.
  fill-item-amount: 1
  #
  # If the fill item will appear enchanted in the GUI.
  fill-item-glowing: true